name: 'CheckFilesFolder'

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  check_files_and_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Folder
        id: chkFolder
        run: |
          if find . -type d -name 'Task[0-9][0-9]-[0-9][0-9]' | grep -q .Task; then 
            echo "Solution folder: Ok."; 
          else 
            echo "Solution folder: Fail."; 
            exit 1;
          fi

      - name: Check projects
        id: chkProjects
        run: |
          if (find . -type f -name *.csproj | grep -q .csproj) then 
            echo "Project files: found."; 
          else 
            echo "Project files: not found."; 
            exit 1;
          fi

      - name: Check report
        id: chkReport
        run: |
          if (find . -type f -name '??? [0-9][0-9][0-9] *.doc*' | grep -q .doc) then 
            echo "Report file: found."; 
          else 
            echo "Report file: not found."; 
            exit 1;
          fi
